// Interactive hole actions (Theme C — intro / split). A floating toolbar appears
// on the hole under the cursor; each action fills the `?` with a well-typed
// skeleton and lets the live checker re-settle.
//
// BelJar IS the intelligence — NOT a slave wrapper of `%:split`/`%:intro` (whose
// printer output is informational and not always re-parseable). The skeleton is
// GENERATED by BelJar from its own model (hole-split.mjs: enumerate the
// scrutinee type's constructors from our AST, read arity/higher-order structure,
// assemble patterns in our grammar). See [[feedback-beljar-not-beluga-wrapper]].
//
// The user-locked CASCADE for each action:
//   1. BelJar generates the skeleton from its model (primary path).
//   2. If BelJar can't model it → ask Beluga (%:split/%:intro), then TRANSFORM the
//      printed answer into our grammar (only if it re-parses); raw printer text is
//      NEVER inserted.
//   3. If even that fails → HONEST-DECLINE: doc untouched + an error toast, which
//      auto-bridges to the persistent Notifications bell (a backlog of cases to
//      teach BelJar later). Never insert broken text.

import { showTooltip } from '@codemirror/view';
import { StateField } from '@codemirror/state';
import { indentRange } from '@codemirror/language';
import { Transaction } from '@codemirror/state';
import { dispatchEdit } from '../edit-history.mjs';
import {
  decomposeContextual,
  headOfConclusion,
  enumerateLFConstructors,
  schemaAdmittedTypes,
  schemaInfo,
  parameterTermFor,
  buildSplitSkeleton,
  buildIntroSkeleton,
  fillCandidates,
} from './hole-split.mjs';

// ── Pure: parse an interactive command's raw output ─────────────────────────
// Beluga prints the new expression terminated by `;`, or an error line led by
// `- ` (e.g. `- No variable n found;`). Returns { ok, text, error }.
export function parseHoleCommandResult(raw) {
  let t = String(raw == null ? '' : raw).replace(/\r\n/g, '\n').trim();
  if (!t) return { ok: false, text: '', error: 'empty' };
  if (t[0] === '-') {
    return { ok: false, text: '', error: t.replace(/^[-\s]+/, '').replace(/;\s*$/, '').trim() };
  }
  t = t.replace(/;\s*$/, '').replace(/\s+$/, '');
  if (!t) return { ok: false, text: '', error: 'empty' };
  return { ok: true, text: t, error: null };
}

// The computation-context variables a `split` can target, in report order.
// Computation-context variables a `split` can MEANINGFULLY target. A variable whose
// reconstructed type is already determined by a context projection (`#p.N[..]`) is
// NOT splittable — splitting it is degenerate (the term is pinned), so it's excluded
// here; the goal there is a `fill`, not a split. (See scrutineeIsParameterDetermined.)
export function splitTargetsOf(hole) {
  if (!hole || !Array.isArray(hole.ctx)) return [];
  return hole.ctx
    .filter((c) => c && c.name && !scrutineeIsParameterDetermined(c.type))
    .map((c) => c.name);
}

// True when intro can plausibly do something — the goal is a function/arrow type
// (intro introduces its binders). A non-arrow goal yields a bare `?` (no-op), so
// we hide the button rather than offer a dead action.
export function canIntro(hole) {
  const g = hole && hole.goal ? String(hole.goal) : '';
  return /->|=>|→/.test(g);
}

const g = () => (typeof window !== 'undefined' ? window : self);

function editorApi() {
  return g().CurrentEditor || null;
}

function belugaClient() {
  return g().BelugaClient || null;
}

function toast(message, kind) {
  const T = g().Toasts;
  if (!T) return;
  if (kind === 'error' && T.error) T.error(message);
  else if (kind === 'success' && T.success) T.success(message);
  else if (T.info) T.info(message);
}

// Honest-decline: BelJar couldn't (and Beluga's transform couldn't) produce a
// well-typed editable step. An error toast AUTO-BRIDGES to the Notifications bell
// (js/toasts.js shouldNotify pushes kind:'error'), so the case becomes a durable
// backlog entry of "something to teach BelJar." Doc is left untouched.
function decline(message) {
  toast(message, 'error');
}

// Doc offset of a hole's `?`, validated against the live doc (null when stale).
function holeOffset(doc, hole) {
  if (!hole || hole.line < 1 || hole.line > doc.lines) return null;
  const off = doc.line(hole.line).from + Math.max(0, (hole.col || 1) - 1);
  if (off >= doc.length) return null;
  return doc.sliceString(off, off + 1) === '?' ? off : null;
}

// The hole (from engine.getHoles) whose `?` token contains `pos`, or null.
export function holeAt(engine, doc, pos) {
  if (!engine || typeof engine.getHoles !== 'function') return null;
  for (const h of engine.getHoles()) {
    const off = holeOffset(doc, h);
    if (off == null) continue;
    let end = off + 1;
    while (end < doc.length && /[^\s([{<:.,;|]/.test(doc.sliceString(end, end + 1))) end += 1;
    if (pos >= off && pos <= end) return { hole: h, from: off, to: off + 1 };
  }
  return null;
}

// Names already in scope at the hole (context + meta vars) — so generated fresh
// metavars don't collide.
function usedNamesAt(hole) {
  const names = [];
  for (const c of (hole.ctx || [])) if (c && c.name) names.push(c.name);
  for (const m of (hole.meta || [])) if (m && m.name) names.push(m.name);
  return names;
}

function currentFileId() {
  const ed = editorApi();
  return ed?.getCurrentFileId?.() ?? null;
}

// Replace the hole's `?` with `text`, re-resolving the `?` against the CURRENT doc
// (it may have shifted while an async step ran) and reindenting the insert.
function insertOverHole(view, engine, hit, text) {
  const live = holeAt(engine, view.state.doc, hit.from);
  const target = live || hit;
  if (view.state.doc.sliceString(target.from, target.to) !== '?') {
    decline('Hole moved — re-check and retry');
    return false;
  }
  const fileId = currentFileId();
  dispatchEdit(view, {
    changes: { from: target.from, to: target.to, insert: text },
    userEvent: 'input.complete',
  }, {
    fileId,
    kind: 'hole',
    followUp: (v) => {
      const ir = indentRange(v.state, target.from, target.from + text.length);
      return ir.empty ? null : { changes: ir, annotations: [Transaction.addToHistory.of(false)] };
    },
  });
  view.focus();
  return true;
}

// Candidate schema names for context variable `ctxVar`, MOST-AUTHORITATIVE FIRST:
// the hole's own meta-context (`g : ctx`, scoped to THIS hole) leads; then every
// distinct `(g : SCHEMA)` binder in the assembled code. A program may bind the same
// name to DIFFERENT schemas in different recs (cp_lemmas binds `g:ctx` for str_hyp
// AND `g:nctx` for str_lin), so we must NOT grab the first global match — the caller
// picks the candidate whose schema actually fits the split's head type.
function candidateSchemasFor(code, hole, ctxVar) {
  const out = [];
  const add = (s) => { if (s && !out.includes(s)) out.push(s); };
  if (!ctxVar) return out;
  const meta = (hole.meta || []).find((m) => m && m.name === ctxVar);
  if (meta && meta.type) add(String(meta.type).trim());
  const re = new RegExp('\\(\\s*' + ctxVar.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\s*:\\s*([A-Za-z_][A-Za-z0-9_\']*)', 'g');
  const src = String(code || '');
  let m;
  while ((m = re.exec(src)) !== null) add(m[1]);
  return out;
}

// ── Step 1: BelJar-native split skeleton from our model ─────────────────────
// Build the case-split skeleton from BelJar's own model: enumerate the scrutinee
// head type's constructors across the WHOLE development (the assembled `code`
// includes the prelude, so cross-file definitions are seen), and add a schema-aware
// parameter-variable branch (`#p.h[..]` block projection) when the context can hold
// a variable of that type — e.g. `hyp` has NO constructors but a hypothesis comes
// from the context (the str_hyp case). Returns the case text, or null when BelJar
// can't model the split (→ cascade to Beluga). `info` (optional out-param) is filled
// with diagnostics for an honest-decline notification.
function belJarSplit(code, hole, varName, info) {
  const note = info || {};
  const entry = (hole.ctx || []).find((c) => c && c.name === varName);
  if (!entry) { note.reason = 'no-such-var'; return null; }
  note.scrutType = entry.type;
  const decomp = decomposeContextual(entry.type);
  if (!decomp) { note.reason = 'non-contextual'; return null; }
  const head = headOfConclusion(decomp.concl);
  if (!head) { note.reason = 'no-head'; return null; }
  note.head = head;

  // Constructors of the head family — across the whole development (assembled code).
  const ctors = enumerateLFConstructors(code, head) || [];
  note.ctorCount = ctors.length;

  // Schema of the leading context variable → block-projection parameter pattern.
  // A name may bind to DIFFERENT schemas in different recs, so pick the candidate
  // whose schema actually admits the head type (a fitting `#p`/`#p.field`); if none
  // fits (a pure constructor split), keep the first candidate for context display.
  const leadCtxVar = decomp.ctx.split(',')[0]?.trim().split(/[\s:]/)[0];
  const candidates = candidateSchemasFor(code, hole, leadCtxVar);
  let schema = null;
  let schemaName = null;
  for (const name of candidates) {
    const info2 = schemaInfo(code, name);
    if (parameterTermFor(head, info2)) { schema = info2; schemaName = name; break; }
  }
  if (!schema && candidates.length) { schemaName = candidates[0]; schema = schemaInfo(code, schemaName); }
  note.schema = schemaName;
  const schemaTypes = schemaName ? schemaAdmittedTypes(code, schemaName) : null;

  const text = buildSplitSkeleton(varName, decomp.ctx, ctors, {
    head,
    schema,
    schemaTypes,
    usedNames: usedNamesAt(hole),
    code, // fixity source: arm annotations must respect --infix declarations
  });
  if (!text) note.reason = ctors.length ? 'no-pattern' : 'no-constructors-no-param';
  return text;
}

// ── Step 1: BelJar-native intro skeleton ────────────────────────────────────
function belJarIntro(hole) {
  return buildIntroSkeleton(hole.goal, { usedNames: usedNamesAt(hole) });
}

// Byte offset of the 1-based (line, col) in a code string.
function offsetOfLineCol(code, line, col) {
  let idx = 0;
  for (let l = 1; l < line; l += 1) {
    const nl = code.indexOf('\n', idx);
    if (nl === -1) return -1;
    idx = nl + 1;
  }
  return idx + (col - 1);
}

// VERIFY a generated step against the REAL hole before inserting — BelJar checking
// BelJar's own work (NOT outsourcing generation to Beluga). Splice `text` over the
// hole's `?` in the assembled `ctx.code` and type-check the whole program; insertion
// only proceeds when it's actually well-formed. This is what categorically prevents
// erroring lines: a skeleton our static model produced that doesn't hold in the
// hole's REAL reconstructed context (e.g. a nested split where the scrutinee is
// already parameter-determined) is caught here and declined instead of inserted.
// Resolves true/false; true (fail-open) only if the checker is unavailable.
async function verifyAtHole(client, ctx, hole, text) {
  if (!client || typeof client.checkResult !== 'function') return true;
  const assembledLine = hole.line + (ctx.offsetLines || 0);
  const off = offsetOfLineCol(ctx.code, assembledLine, hole.col);
  if (off < 0 || off >= ctx.code.length || ctx.code.charAt(off) !== '?') return true;
  const spliced = ctx.code.slice(0, off) + text + ctx.code.slice(off + 1);
  try {
    const r = await client.checkResult(spliced);
    return !!(r && r.ok);
  } catch (e) {
    if (client.isCancelledError && client.isCancelledError(e)) return false;
    return true; // checker error ≠ skeleton invalid; don't block on infra failure
  }
}

// Is the scrutinee ALREADY pinned to a context-variable projection? When a hole's
// reconstructed scrutinee type carries a parameter projection (`#p.1[..]`,
// `#p.h[..]`) in its conclusion, the term is already determined by a context entry —
// splitting it again is degenerate (Beluga itself only emits `let [_ ⊢ #p.N] = v`,
// which isn't editable). Read from the hole's OWN reconstructed type, not the source
// signature — this is the dependency the static model can't see.
export function scrutineeIsParameterDetermined(scrutType) {
  return /#[A-Za-z0-9_]*\.[A-Za-z0-9_]+/.test(String(scrutType || ''));
}

// ── Step 2: Beluga fallback + TRANSFORM into our grammar ────────────────────
// When BelJar can't model the step, ask Beluga's prover, then re-express its
// answer in our pattern grammar. We only accept a transform that RE-PARSES as a
// well-typed step (verified by splicing + check on the client side); raw printer
// text (`let [_, x1 ⊢ #p.2[..]]`) is never inserted. Returns the editable text or
// null (→ honest-decline). Async.
async function belugaFallback(client, ctx, hole, cmd) {
  const assembledLine = hole.line + (ctx.offsetLines || 0);
  let res;
  try {
    res = await client.holeAction(ctx.code, assembledLine, hole.col, cmd);
  } catch (e) {
    if (client.isCancelledError && client.isCancelledError(e)) return { cancelled: true };
    return null;
  }
  if (!res || !res.ok) {
    return { why: res && res.error === 'load-failed' ? 'the file has errors' : 'Beluga couldn’t run the step' };
  }
  const parsed = parseHoleCommandResult(res.output);
  if (!parsed.ok) return { why: parsed.error ? `Beluga: ${parsed.error}` : 'Beluga produced no step' };
  const transformed = transformBelugaStep(parsed.text);
  if (transformed) return { text: transformed };
  return { why: 'Beluga printed a non-editable step (e.g. `let [_, … ⊢ #p.N[..]]`).' };
}

// Rewrite a Beluga prover step into OUR grammar where we can. A plain re-parseable
// case/expression passes through; the known non-reparseable shape (a context split
// printed as `let [_, x1, x2 ⊢ #p.2[..]] = v in ?`) is rejected here (returns null
// → honest-decline) rather than guessed at. (Future: teach specific transforms.)
export function transformBelugaStep(text) {
  const t = String(text == null ? '' : text).trim();
  if (!t) return null;
  // The projection/anonymous context-pattern form the surface parser rejects.
  if (/\blet\s+\[[^\]]*\b_\b[^\]]*[|⊢][^\]]*#/.test(t)) return null;
  if (/#[A-Za-z0-9_]*\.\d/.test(t)) return null; // `#p.2[..]` projections
  return t;
}

// Build a DETAILED decline message so the Notifications backlog is actionable —
// it must say WHICH split, on WHAT type, in WHAT context, and WHY BelJar couldn't
// model it (so the case can actually be taught). `extra` describes why Beluga's
// fallback also failed.
function splitDeclineMessage(varName, note, extra) {
  const head = note.head ? ` of type \`${note.head}\`` : '';
  const where = note.scrutType ? ` (\`${varName} : ${note.scrutType}\`)` : '';
  let why;
  switch (note.reason) {
    case 'non-contextual': why = `\`${varName}\` isn’t a boxed contextual term`; break;
    case 'no-head': why = `couldn’t read the scrutinee’s head type`; break;
    case 'no-constructors-no-param':
      why = `\`${note.head}\` has no constructors and no schema variable fits` +
            (note.schema ? ` (context schema \`${note.schema}\`)` : ` (no context schema found)`);
      break;
    case 'no-pattern': why = `couldn’t assemble patterns for \`${note.head}\``; break;
    case 'verify-failed': why = `the generated \`${note.head}\` split didn’t type-check at this hole (its real context has dependencies the pattern doesn’t satisfy)`; break;
    default: why = `BelJar can’t model this split yet`;
  }
  return `Split ${varName}${head}${where}: ${why}. ${extra || 'Beluga’s fallback wasn’t editable either.'} Logged to teach BelJar.`;
}

// ── fill: prove the goal directly with a verified inhabiting term ───────────
// Generate candidate terms from BelJar's model (fillCandidates), verify each at the
// REAL hole, and insert the FIRST that type-checks. Returns true when a fill landed.
// This is how a goal that's directly provable (a hypothesis projection, a returned
// variable, a nullary constructor) gets COMPLETED rather than declined.
async function tryFill(view, engine, hit, ctx, client) {
  const cands = fillCandidates(hit.hole, ctx.code);
  for (const term of cands) {
    if (await verifyAtHole(client, ctx, hit.hole, term)) {
      insertOverHole(view, engine, hit, term);
      return true;
    }
  }
  return false;
}

// ── Split action (the cascade) ──────────────────────────────────────────────
// The cascade, each step gated by a REAL verification against the hole:
//   0. scrutinee already determined by a context variable → it's not a split, the
//      goal is directly provable → FILL it with a verified inhabiting term.
//   1. BelJar generates a split from its model → VERIFY at the hole → insert.
//   2. else Beluga fallback + transform → VERIFY → insert if it holds.
//   3. else (last resort) try a fill; else honest-decline with a detailed reason.
// Nothing is inserted that doesn't actually type-check at the real hole.
export async function runSplit(view, engine, hit, varName) {
  const api = editorApi();
  const client = belugaClient();
  if (!api) return;
  const ctx = typeof api.getHoleActionContext === 'function' ? api.getHoleActionContext() : null;
  if (!ctx || !ctx.code) return;
  const hole = hit.hole;
  const entry = (hole.ctx || []).find((c) => c && c.name === varName);

  // 0. Already determined by a context variable → this isn't a split; the goal is
  //    directly provable. FILL it (the str_hyp inner-hole case: `[g |- #p.h[..]]`).
  if (entry && scrutineeIsParameterDetermined(entry.type)) {
    if (await tryFill(view, engine, hit, ctx, client)) return;
    decline(`Split ${varName}: \`${varName}\` is already determined by a context variable, and BelJar couldn’t find an inhabiting term for the goal \`${hole.goal}\`. Logged to teach BelJar.`);
    return;
  }

  // 1. BelJar generates from its own model, then verifies it at the REAL hole.
  const note = {};
  const own = belJarSplit(ctx.code, hole, varName, note);
  if (own) {
    if (await verifyAtHole(client, ctx, hole, own)) { insertOverHole(view, engine, hit, own); return; }
    note.verifyFailed = true;
  }

  // 2. Beluga fallback + transform — also verified before inserting.
  let fallbackWhy = null;
  if (client && typeof client.holeAction === 'function') {
    const fb = await belugaFallback(client, ctx, hole, 'split ' + varName);
    if (fb && fb.cancelled) return;
    if (fb && fb.text && await verifyAtHole(client, ctx, hole, fb.text)) {
      insertOverHole(view, engine, hit, fb.text); return;
    }
    fallbackWhy = fb && fb.why ? fb.why
      : (fb && fb.text ? 'Beluga’s step didn’t type-check at this hole.'
        : 'Beluga printed a non-editable step (a context/parameter split it can’t express as source).');
  }

  // 3. Last resort: the goal may be directly provable even if a split isn't — try a
  //    verified fill before giving up.
  if (await tryFill(view, engine, hit, ctx, client)) return;

  // 4. Honest-decline → detailed Notifications backlog entry.
  if (note.verifyFailed && !note.reason) note.reason = 'verify-failed';
  decline(splitDeclineMessage(varName, note, fallbackWhy));
}

// ── Fill action (toolbar button) ────────────────────────────────────────────
export async function runFill(view, engine, hit) {
  const api = editorApi();
  const client = belugaClient();
  if (!api) return;
  const ctx = typeof api.getHoleActionContext === 'function' ? api.getHoleActionContext() : null;
  if (!ctx || !ctx.code) return;
  if (await tryFill(view, engine, hit, ctx, client)) return;
  decline(`Fill: BelJar couldn’t find an inhabiting term for \`${hit.hole.goal}\`. Logged to teach BelJar.`);
}

// ── Intro action (the cascade) ──────────────────────────────────────────────
export async function runIntro(view, engine, hit) {
  const api = editorApi();
  const client = belugaClient();
  if (!api) return;
  const ctx = typeof api.getHoleActionContext === 'function' ? api.getHoleActionContext() : null;
  if (!ctx || !ctx.code) return;
  const hole = hit.hole;

  const own = belJarIntro(hole);
  if (own && await verifyAtHole(client, ctx, hole, own)) { insertOverHole(view, engine, hit, own); return; }

  if (client && typeof client.holeAction === 'function') {
    const fb = await belugaFallback(client, ctx, hole, 'intro');
    if (fb && fb.cancelled) return;
    if (fb && fb.text && await verifyAtHole(client, ctx, hole, fb.text)) { insertOverHole(view, engine, hit, fb.text); return; }
  }

  decline('Can’t introduce binders here yet — logged to notifications to teach BelJar');
}

// The assembled checker code (for constructor lookup in fill candidates), or ''.
function holeCtxCode() {
  const api = editorApi();
  const ctx = api && typeof api.getHoleActionContext === 'function' ? api.getHoleActionContext() : null;
  return (ctx && ctx.code) || '';
}

// ── Floating toolbar (a CM tooltip anchored on the focused hole) ────────────
function buildToolbar(view, engine, hit) {
  const dom = document.createElement('div');
  dom.className = 'bel-hole-toolbar';

  const hole = hit.hole;
  const mkBtn = (label, title, onClick) => {
    const b = document.createElement('button');
    b.type = 'button';
    b.className = 'bel-hole-action';
    b.textContent = label;
    if (title) b.title = title;
    b.addEventListener('mousedown', (e) => { e.preventDefault(); });
    b.addEventListener('click', (e) => {
      e.preventDefault();
      e.stopPropagation();
      onClick();
    });
    return b;
  };

  // "prove" — open the interactive Harpoon (drives the real Harpoon tactic
  // engine, renders BelJar's own subgoal tree / tactic palette / preview). The
  // inline intro/split/fill buttons stay for quick single-step edits; the Lab is
  // the deeper surface for proving a whole declaration interactively.
  const lab = g().Harpoon;
  if (lab && typeof lab.openFromHole === 'function') {
    dom.appendChild(mkBtn('prove', 'Prove interactively in the Harpoon', () => {
      lab.openFromHole(view, engine, hit);
    }));
  }

  if (canIntro(hole)) {
    dom.appendChild(mkBtn('intro', 'Introduce the goal’s binders', () => {
      runIntro(view, engine, hit);
    }));
  }

  // `fill` — offered when BelJar can propose an inhabiting term for the goal (a
  // hypothesis projection, a returned variable, a nullary constructor). The actual
  // term is verified at click time; the button just signals "this goal looks
  // directly provable". A `?`-determined scrutinee makes split degenerate, so fill
  // is the meaningful action there (the str_hyp inner hole).
  if (fillCandidates(hole, holeCtxCode()).length) {
    dom.appendChild(mkBtn('fill', 'Prove this goal with an inhabiting term', () => {
      runFill(view, engine, hit);
    }));
  }

  const vars = splitTargetsOf(hole);
  if (vars.length) {
    const wrap = document.createElement('span');
    wrap.className = 'bel-hole-split-group';
    const lead = document.createElement('span');
    lead.className = 'bel-hole-split-label';
    lead.textContent = 'split';
    wrap.appendChild(lead);
    for (const v of vars) {
      wrap.appendChild(mkBtn(v, 'Case-split on ' + v, () => {
        runSplit(view, engine, hit, v);
      }));
    }
    dom.appendChild(wrap);
  }

  if (!dom.childElementCount) return null;
  return { pos: hit.from, above: true, arrow: false, create: () => ({ dom }) };
}

// A StateField providing at most one hole-action tooltip — when the cursor sits
// on a `?` that the checker has typed (so we know its goal/context). Recomputes on
// selection or doc change, and when the hole set shifts (settlement transaction).
export function holeActionToolbar(engine) {
  const compute = (state) => {
    const sel = state.selection.main;
    if (!sel.empty) return null;
    const hit = holeAt(engine, state.doc, sel.head);
    if (!hit) return null;
    // Need a typed hole to offer meaningful actions.
    if (!hit.hole.goal && !(hit.hole.ctx && hit.hole.ctx.length)) return null;
    // Tooltip `create` runs with a live view; stash the hit on the field value.
    return { hit };
  };
  return StateField.define({
    create: (state) => compute(state),
    update(value, tr) {
      if (!tr.docChanged && !tr.selection && !tr.effects.length) return value;
      return compute(tr.state);
    },
    provide: (f) =>
      showTooltip.compute([f], (state) => {
        const v = state.field(f);
        if (!v) return null;
        // `create` receives the view; rebuild the toolbar there so handlers close
        // over the live view + current hit.
        return {
          pos: v.hit.from,
          above: true,
          arrow: false,
          create: (view) => {
            const tip = buildToolbar(view, engine, v.hit);
            if (tip && tip.create) return tip.create();
            const dom = document.createElement('div');
            dom.className = 'bel-hole-toolbar';
            return { dom };
          },
        };
      }),
  });
}
