// Manual Harpoon — the interactive proof session as a PURE reducer.
//
// BelJar drives: every move offered here is generated by our own semantic model
// (`candidateMoves`), and Beluga is the ORACLE that certifies the one the user
// picked. This module never touches the DOM or the client; the Lab passes an
// `oracle(code) -> Promise<{ok, output}>` in, exactly as `proveProgram` does, so
// the whole session is testable in node with a stub.
//
// The session is a WORKING COPY of the assembled prove-program plus a snapshot
// stack. Applying a move is: splice the candidate over the focus hole's `?` →
// check the spliced program ONCE → the same checker output carries the new
// `## Holes ##` report, so the successor state costs no extra call.
//
// ── Why this is not `proveProgramCore` with maxSteps:1 ──────────────────────
// The search loop's per-candidate attempt is entangled with wave batching, the
// E.9 `certifyTrim` arbitration, the reject cache and the search guards
// (revisit fingerprint, α-regress, zero-progress + speculative-let budgets).
// Those guards are SEARCH CONTROL, not soundness — a human who picks a move
// meant it, and must not be told "that revisits a seen state". And the trim is a
// cost optimization for a search making thousands of checks; we make one per
// click. So the manual attempt is the honest minimum:
//
//     splice → oracle(FULL program) → if split: prune arms → error-count verdict
//
// which leaves `proveProgramCore` untouched.

import {
  candidateMoves,
  movePrefilterOk,
  countErrors,
  firstErrorOf,
  pruneOneBranch,
  caseArmLine,
  scoreHole,
} from './prover-orchestrator.mjs';
import { stepMeta, stepLead } from './prover-captions.mjs';
import { parseHoles } from './hole-report.mjs';
import {
  spliceAtHole,
  holesForTheorem,
  normalizeHoleCol,
} from './prover-certify.mjs';
import { enrichHoleFromTheorem, resolveHoleGoal, branchPatternBox } from './prover-hyp.mjs';

// A hole straight out of the report is NOT ready for `candidateMoves` — the
// three-step preparation below is mandatory, and skipping any of it silently
// degrades the offered moves (see the prover handbook §5 invariant 11 on the
// report's namespace differing from the source's).
function prepareHole(hole, thm, code) {
  return resolveHoleGoal(normalizeHoleCol(code, enrichHoleFromTheorem(hole, thm, code)), thm);
}

// The engine's OWN focus rule, so manual and Brutus agree on "the current
// subgoal": the leftmost enclosing case-arm, then the highest-scoring hole
// within that arm.
function defaultFocusIdx(holes, code) {
  if (!holes.length) return -1;
  const armLines = holes.map((h) => caseArmLine(code, h));
  const focusArm = Math.min(...armLines);
  let best = -1;
  let bestScore = -Infinity;
  holes.forEach((h, i) => {
    if (armLines[i] !== focusArm) return;
    const s = scoreHole(h, code);
    if (s > bestScore) { bestScore = s; best = i; }
  });
  return best;
}

/**
 * Build a session state from a checker result over `code`.
 * `checkerOutput` is the raw output of a check on `code` — the same string the
 * search loop parses. Returns null when the program has no hole for this theorem.
 */
export function manualState(code, thm, checkerOutput) {
  const holes = holesForTheorem(code, thm, parseHoles(checkerOutput || ''))
    .map((h) => prepareHole(h, thm, code));
  return {
    code: String(code || ''),
    holes,
    focusIdx: defaultFocusIdx(holes, code),
    steps: [],
    stack: [],
    future: [],
  };
}

/** The hole the user is standing at, or null when the proof is complete. */
export function focusHole(state) {
  if (!state || state.focusIdx < 0) return null;
  return state.holes[state.focusIdx] || null;
}

export function isComplete(state) {
  return !!state && state.holes.length === 0;
}

/** Move the focus (Harpoon's `defer` / subgoal selection). */
export function focusOn(state, idx) {
  if (!state || idx < 0 || idx >= state.holes.length || idx === state.focusIdx) return state;
  return { ...state, focusIdx: idx };
}

/**
 * The ranked candidate moves at the focus hole, sound-prefiltered.
 *
 * `movePrefilterOk` rejects only candidates the checker would PROVABLY reject
 * (quoted internal names, bare `#p`/`$S` in comp slots, family/scope clashes),
 * so filtering here costs the user nothing and keeps the menu honest.
 */
export function movesAt(state, thm) {
  const hole = focusHole(state);
  if (!hole) return [];
  let moves = candidateMoves(hole, state.code, thm) || [];
  moves = moves.filter((mv) => movePrefilterOk(mv, hole, state.code, { trustScope: true }));
  // The search's own last resort: a hole whose context blocks every move still
  // deserves an offer. Mirror it rather than showing the user an empty menu.
  if (!moves.length && hole.ctx && hole.ctx.length) {
    const bare = { ...hole, ctx: [] };
    moves = (candidateMoves(bare, state.code, thm) || [])
      .filter((mv) => movePrefilterOk(mv, bare, state.code, { trustScope: true }));
  }
  return moves;
}

/**
 * Attempt ONE candidate at the focus hole. Does not mutate `state`.
 *
 * Resolves `{ ok, text, spliced, output, error }`. `text` is the move text that
 * ACTUALLY certified, which for a split is usually not `mv.text`: splits are
 * emitted with every constructor's arm, and Beluga expects arms its coverage
 * checker infers impossible to be OMITTED. `pruneOneBranch` drops the arm the
 * checker's error points into and we re-verify, exactly as the search does —
 * without it most splits simply never certify.
 */
export async function attemptMove(state, mv, oracle, thm) {
  const hole = focusHole(state);
  if (!hole) return { ok: false, error: 'no open hole' };
  let text = mv.text;
  let spliced = spliceAtHole(state.code, hole, text);
  if (spliced == null) return { ok: false, error: 'the move could not be placed at this hole' };

  let res = await oracle(spliced);

  if (mv.kind === 'split') {
    let guard = (text.match(/^\s*\|/gm) || []).length;
    while ((!res || !res.ok || countErrors(res) > 0) && guard-- > 0) {
      const next = pruneOneBranch(text, res && res.output, hole);
      if (!next) break;
      const nextSpliced = spliceAtHole(state.code, hole, next);
      if (nextSpliced == null) break;
      text = next;
      spliced = nextSpliced;
      res = await oracle(spliced);
    }
  }

  if (!res || !res.ok || countErrors(res) > 0) {
    return {
      ok: false,
      text,
      spliced,
      output: res && res.output,
      forCode: state.code,
      error: (res && firstErrorOf(res.output)) || 'the checker did not accept this move',
    };
  }
  // `forCode` stamps which program this verdict was reached against, so a caller
  // can safely REUSE it instead of paying for the same check twice (see
  // `applyMove`). Without the stamp there is no way to know a cached result has
  // not been invalidated by an intervening move.
  return { ok: true, text, spliced, output: res.output, forCode: state.code };
}

/**
 * The step record for an accepted move.
 *
 * Deliberately the SAME shape auto-solve pushes, so the solve reel, the
 * derivation list and `HarpoonTree.buildModel` render a manual proof with no
 * new code. Auto-only fields (`focus` — the search's arm-scoring metadata; `zp`
 * — the zero-progress budget flag) have no manual meaning and are omitted
 * rather than faked; the tree model reads `meta.armPatterns`/`meta.chain` and
 * tolerates their absence.
 */
function buildStep(hole, mv, text, code, nextHoles) {
  const meta = stepMeta(mv, text, hole);
  return {
    move: mv.kind,
    lead: stepLead(mv, meta, hole),
    rationale: stepLead(mv, meta, hole),
    meta,
    checks: 1,
    goal: hole.goal,
    hole: { line: hole.line, col: hole.col, name: hole.name || null },
    holeCtx: hole.ctx || [],
    holeMeta: hole.meta || [],
    branch: branchPatternBox(code, hole),
    text,
    status: nextHoles.length ? 'open' : 'solved',
    manual: true,
  };
}

function snapshot(state) {
  return { code: state.code, holes: state.holes, focusIdx: state.focusIdx, steps: state.steps };
}

/**
 * Apply a move: attempt it, and on success return the successor state with the
 * step recorded and the snapshot pushed for undo. On failure the state is
 * returned UNCHANGED alongside the checker's objection, so the picker can show
 * why a move the user chose did not hold.
 */
export async function applyMove(state, mv, oracle, thm, precomputed) {
  const hole = focusHole(state);
  // A move the background sweep already certified needs no second check: that
  // pass produced the spliced program AND the checker output the successor
  // state is built from, so re-running it is pure duplicated cost. Only trust
  // the cache when it was reached against THIS exact program.
  const cached = precomputed && precomputed.ok && precomputed.forCode === state.code
    ? precomputed
    : null;
  const r = cached || await attemptMove(state, mv, oracle, thm);
  if (!r.ok) return { state, ok: false, error: r.error, output: r.output };

  const holes = holesForTheorem(r.spliced, thm, parseHoles(r.output || ''))
    .map((h) => prepareHole(h, thm, r.spliced));
  const step = buildStep(hole, mv, r.text, state.code, holes);
  return {
    ok: true,
    state: {
      code: r.spliced,
      holes,
      focusIdx: defaultFocusIdx(holes, r.spliced),
      steps: [...state.steps, step],
      stack: [...state.stack, snapshot(state)],
      future: [],
    },
    step,
  };
}

/**
 * Fold a Brutus (auto-solve) run into the session, so a mid-proof search reads
 * as a continuation of the same trail rather than a separate event. `result` is
 * a `proveProgram` return value.
 */
export function absorbAuto(state, result, thm) {
  if (!result || !result.code) return state;
  const holes = result.complete
    ? []
    : holesForTheorem(result.code, thm, parseHoles(result.output || ''))
      .map((h) => prepareHole(h, thm, result.code));
  return {
    code: result.code,
    holes,
    focusIdx: defaultFocusIdx(holes, result.code),
    steps: [...state.steps, ...(result.steps || [])],
    stack: [...state.stack, snapshot(state)],
    future: [],
  };
}

export function canUndo(state) { return !!state && state.stack.length > 0; }
export function canRedo(state) { return !!state && state.future.length > 0; }

export function undo(state) {
  if (!canUndo(state)) return state;
  const prev = state.stack[state.stack.length - 1];
  return {
    ...prev,
    stack: state.stack.slice(0, -1),
    future: [...state.future, snapshot(state)],
  };
}

export function redo(state) {
  if (!canRedo(state)) return state;
  const next = state.future[state.future.length - 1];
  return {
    ...next,
    stack: [...state.stack, snapshot(state)],
    future: state.future.slice(0, -1),
  };
}
