import globals from 'globals';

/** Window globals published by the shell / editor seam (system nouns). */
const SHELL_GLOBALS = [
  'AvailableMacros',
  'BelEditor',
  'BelugaClient',
  'BelugaRun',
  'CommandBar',
  'CommandPalette',
  'Commands',
  'ConfirmDialog',
  'ConflictDialog',
  'CurrentEditor',
  'Dialog',
  'DoubleTap',
  'DownloadZip',
  'Dropdown',
  'EditHistory',
  'EditHistoryInstall',
  'Explorer',
  'ExplorerInlineName',
  'ExplorerSearch',
  'ExplorerSuiteLayout',
  'FloatingRectPlacement',
  'FloatingWindow',
  'Frame',
  'FullKeyboard',
  'Harpoon',
  'HarpoonEngine',
  'HarpoonPanel',
  'HeaderSearch',
  'Hint',
  'Keybindings',
  'Library',
  'LibraryPreview',
  'LibrarySearch',
  'LibrarySuites',
  'LiveIntel',
  'Menu',
  'NameConflicts',
  'NamePrompt',
  'Notifications',
  'Perf',
  'Persist',
  'ProjectSource',
  'PromptDialog',
  'Repl',
  'ReplAutocomplete',
  'ReplCommands',
  'ReplOutput',
  'ReplPersist',
  'ReplRunCmd',
  'ReplStream',
  'RunProgress',
  'ScrollFade',
  'SettingsUI',
  'SidePanelResize',
  'StatusStrip',
  'Toasts',
  'Toggle',
  'Tooltips',
  'WorkspaceSplit',
  'WorkspaceState',
  'BelJarBelugaRun',
  'BelJarConfirmDialog',
  'BelJarConflictDialog',
  'BelJarCurrentEditor',
  'BelJarDialog',
  'BelJarEditHistory',
  'BelJarEditHistoryInstall',
  'BelJarEditor',
  'BelJarExplorer',
  'BelJarExplorerInlineName',
  'BelJarExplorerSearch',
  'BelJarExplorerSuiteLayout',
  'BelJarHarpoon',
  'BelJarHarpoonEngine',
  'BelJarHarpoonPanel',
  'BelJarHeaderSearch',
  'BelJarKeybindings',
  'BelJarLibrary',
  'BelJarLibraryPreview',
  'BelJarLibrarySearch',
  'BelJarLibrarySuites',
  'BelJarNameConflicts',
  'BelJarNamePrompt',
  'BelJarNotifications',
  'BelJarPersist',
  'BelJarProjectSource',
  'BelJarPromptDialog',
  'BelJarReplCommands',
  'BelJarReplOutput',
  'BelJarSettingsUI',
  'BelJarSidePanelResize',
  'BelJarToasts',
  'BelJarToggle',
  'BelJarWorkspaceSplit',
  'BelJarWorkspaceState',
  'BelugaText',
];

const shellGlobalsMap = Object.fromEntries(
  SHELL_GLOBALS.map((name) => [name, 'readonly']),
);

const baseRules = {
  'no-unused-vars': ['warn', {
    args: 'none',
    caughtErrors: 'none',
    varsIgnorePattern: '^_',
    ignoreRestSiblings: true,
  }],
  'no-undef': 'error',
};

/** @type {import('eslint').Linter.Config[]} */
export default [
  {
    ignores: [
      'js/editor-cm.bundle.js',
      'js/ui/tooltips.js',
      // Generated IIFE leaves — lint the matching `.mjs` sources instead.
      'js/**/*.js',
      '!js/beluga/beluga-client.js',
      '!js/beluga/beluga-worker.js',
      '!js/harpoon/harpoon-client.js',
    ],
  },
  {
    files: ['js/beluga/beluga-worker.js', 'js/beluga/beluga-client.js', 'js/harpoon/harpoon-client.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...globals.worker,
        ...shellGlobalsMap,
      },
    },
    rules: baseRules,
  },
  {
    files: ['js/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...shellGlobalsMap,
        CodeMirror: 'readonly',
      },
    },
    rules: baseRules,
  },
];
