import globals from 'globals';

/** @type {import('eslint').Linter.Config[]} */
export default [
  {
    ignores: ['js/editor-cm.bundle.js'],
  },
  {
    files: ['js/beluga-worker.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: { ...globals.browser, ...globals.worker },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-undef': 'error',
    },
  },
  {
    files: ['js/*.js'],
    ignores: ['js/beluga-worker.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        BelugaText: 'readonly',
        BelJarPersist: 'readonly',
        BelJarWorkspaceState: 'readonly',
        BelJarEditor: 'readonly',
        BelJarDialog: 'readonly',
        BelJarPromptDialog: 'readonly',
        BelJarConfirmDialog: 'readonly',
        BelJarToggle: 'readonly',
        BelJarWorkspaceSplit: 'readonly',
        BelJarSidePanelResize: 'readonly',
        BelJarReplOutput: 'readonly',
        BelJarBelugaRun: 'readonly',
        BelJarReplCommands: 'readonly',
        BelJarSettingsUI: 'readonly',
        BelJarCurrentEditor: 'readonly',
        LiveIntel: 'readonly',
        BelugaClient: 'readonly',
        RunProgress: 'readonly',
        FloatingRectPlacement: 'readonly',
        Menu: 'readonly',
        Tooltips: 'readonly',
        FloatingWindow: 'readonly',
        ScrollFade: 'readonly',
        CommandPalette: 'readonly',
        BelJarProjectSource: 'readonly',
        BelJarNameConflicts: 'readonly',
        BelJarConflictDialog: 'readonly',
        BelJarToasts: 'readonly',
        BelJarNotifications: 'readonly',
        BelJarExplorer: 'readonly',
        BelJarExplorerInlineName: 'readonly',
        BelJarExplorerSearch: 'readonly',
        BelJarExplorerSuiteLayout: 'readonly',
        BelJarHeaderSearch: 'readonly',
        BelJarLibrary: 'readonly',
        BelJarLibrarySearch: 'readonly',
        BelJarLibrarySuites: 'readonly',
        BelJarNamePrompt: 'readonly',
        BelJarHarpoonEngine: 'readonly',
        BelJarHarpoonIcon: 'readonly',
        BelJarHarpoon: 'readonly',
        BelJarHarpoonPanel: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-undef': 'error',
    },
  },
  {
    files: ['editor-src/**/*.mjs'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      'no-unused-vars': ['warn', { args: 'none', caughtErrors: 'none' }],
      'no-undef': 'error',
    },
  },
];
